# Generated by Django 5.2.8 on 2025-11-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member_management", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Familie",
            new_name="Family",
        ),
        migrations.AlterModelOptions(
            name="family",
            options={"verbose_name": "Family", "verbose_name_plural": "Families"},
        ),
        migrations.AlterModelOptions(
            name="member",
            options={"verbose_name": "Member", "verbose_name_plural": "Members"},
        ),
        migrations.AlterModelOptions(
            name="vistor",
            options={"verbose_name": "Vistor", "verbose_name_plural": "Vistors"},
        ),
        migrations.AddField(
            model_name="member",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="date_of_birth",
            field=models.DateField(
                help_text="Provide the member's date of birth (MM/DD/YYYY).",
                null=True,
                verbose_name="Date of Birth",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="member",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S", "Single"),
                    ("M", "Married"),
                    ("D", "Divorced"),
                    ("W", "Widowed"),
                ],
                default="S",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="phone_number",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                max_length=1,
                null=True,
            ),
        ),
    ]
