# Generated by Django 5.2.7 on 2025-11-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "member_management",
            "0002_rename_familie_family_alter_family_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="vistor",
            name="date_of_birth",
            field=models.DateField(
                help_text="Provide the member's date of birth (MM/DD/YYYY).",
                null=True,
                verbose_name="Date of Birth",
            ),
        ),
        migrations.AddField(
            model_name="vistor",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="vistor",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vistor",
            name="phone_number",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
