# Generated by Django 5.2.8 on 2025-12-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_management', '0004_role_userprofile_rolesandministries_usersandroles'),
        ('ministry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vistor',
            options={'verbose_name': 'Visitor', 'verbose_name_plural': 'Visitors'},
        ),
        migrations.RemoveField(
            model_name='vistor',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='vistor',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistor',
            name='age_group',
            field=models.CharField(blank=True, choices=[('Under 18', 'Under 18'), ('18-24', '18-24'), ('25-34', '25-34'), ('35-44', '35-44'), ('45-54', '45-54'), ('55-64', '55-64'), ('65+', '65+')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vistor',
            name='dedicated_to_christ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vistor',
            name='how_found',
            field=models.TextField(blank=True, help_text='Comma-separated list of sources (e.g., Social Media, Friend, Website)', null=True),
        ),
        migrations.AddField(
            model_name='vistor',
            name='interested_ministries',
            field=models.ManyToManyField(blank=True, related_name='interested_visitors', to='ministry.ministry'),
        ),
        migrations.AddField(
            model_name='vistor',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='vistor',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistor',
            name='rededicated_to_christ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vistor',
            name='request_contact_by_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vistor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
