# Generated by Django 5.2.8 on 2025-12-04 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member_management', '0005_alter_vistor_options_remove_vistor_date_of_birth_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
