# Generated by Django 5.2.7 on 2025-11-19 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "member_management",
            "0003_vistor_date_of_birth_vistor_email_vistor_gender_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MembersAndMinistries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("Member", "Member"), ("Leader", "Leader")],
                        default="Member",
                        max_length=50,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="member_management.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ministry Membership",
                "verbose_name_plural": "Ministry Memberships",
            },
        ),
        migrations.CreateModel(
            name="Ministry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ministry_name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "leader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="member_management.member",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="church_groups",
                        through="ministry.MembersAndMinistries",
                        to="member_management.member",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Ministries",
            },
        ),
        migrations.AddField(
            model_name="membersandministries",
            name="ministry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ministry.ministry"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="membersandministries",
            unique_together={("member", "ministry")},
        ),
    ]
