# Generated by Django 5.2.8 on 2025-12-03 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_event_event_type_event_event_description_and_more'),
        ('ministry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ministry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='ministry.ministry'),
        ),
    ]
