# Generated by Django 5.2.8 on 2025-12-03 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_event_ministry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventschedule',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='eventschedule',
            name='start_date',
        ),
    ]
