# Generated by Django 5.2.8 on 2025-12-03 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_eventschedule_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
    ]
